name: Daily MongoDB Backup

on:
  schedule:
    # Run daily at 1 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  backup-mongodb:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo python-dotenv tqdm
      
      - name: Create .env file with backup settings
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
          echo "MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}" >> .env
          echo "MONGO_COLLECTION=${{ secrets.MONGO_COLLECTION }}" >> .env
          echo "EMBEDDING_API_URL=${{ secrets.EMBEDDING_API_URL }}" >> .env
          echo "VERIFY_SSL=${{ secrets.VERIFY_SSL || 'true' }}" >> .env
          echo "BACKUP_DIR=${{ github.workspace }}/backups" >> .env
          echo "DAILY_RETENTION=${{ secrets.DAILY_RETENTION || '7' }}" >> .env
          echo "WEEKLY_RETENTION=${{ secrets.WEEKLY_RETENTION || '4' }}" >> .env
          echo "MONTHLY_RETENTION=${{ secrets.MONTHLY_RETENTION || '6' }}" >> .env
      
      - name: Create backup directory
        run: mkdir -p backups
      
      - name: Run MongoDB backup
        run: python src/[LOOP]_backup_mongo.py
      
      - name: Upload backup as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mongodb-backup-${{ github.run_id }}
          path: backups/
          retention-days: 7